source "https://rubygems.org"
ruby "3.2.0"

gem "rails", "~> 7.1"
gem "sqlite3", "~> 1.4"        # Use pg for PostgreSQL
gem "puma", ">= 5.0"
gem "rack-cors"

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers", "~> 5.0"
  gem "database_cleaner-active_record"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"               # Auto-manages ChromeDriver
end
